import { Product } from "./types/types";

export const TEST_PRODUCTS: Product[] = [
  {
    id: 12,
    displayName: "The Paws Dog Accessory",
    description:
      "This bandana is tailor-cut and double-sided for easy tying and the perfect fit.\\n    It features a classic baseball design on a sky-blue cotton fabric for eye-catching appeal.\\n    For convenience, this bandana is made with 100% cotton that washes well multiple times.\\n    With all breeds in mind, this bandana is available in different sizes to fit pups of all sizes.\\n    Designed by The Paws for family fun and a game-day look that will have your tail wagger ready to chase that ball.\\n\\nRemember to measure your pet for the perfect fit. Get your pup ready for game day with The Paws Home Run Dog Bandana. This classic bandana features baseballs flying on a sky-blue cotton fabric, perfect for the furry favorites on your team. Each bandana is tailor-cut and double-sided, making it easy to tie on and sized just right for your furry friend. Inspired by tropical and urban locations, The Paws loves to mix bright colors with subtle tones and unique designs. Plus, each bandana is thoughtfully made on the island of Bali by experienced and skilled teams.",
    manufacturer: {
      id: 4,
      displayName: "The Paws",
      createdAt: "2025-04-24T08:51:55.718Z",
      updatedAt: "2025-04-24T08:51:55.718Z",
      deletedAt: null,
      version: 1,
    },
    price: 17.25,
    rating: 4.25,
    reviews: 0,
    category: "Dog Accessories",
    type: "bandana",
    colors: [
      {
        id: 12,
        major: "blue",
        sub: "soft blue",
        r: 140,
        g: 200,
        b: 227,
      },
    ],
    size: "X-Large",
    weightRange: "[0,999]",
    season: "Year-Round",
    materials: [
      {
        id: 12,
        name: "Cotton",
        createdAt: "2025-04-24T08:51:55.733Z",
        deletedAt: null,
      },
    ],
    instructions: "Machine wash, tumble dry.",
    images: [
      {
        id: 12,
        url: "https://image.chewy.com/catalog/general/images/moe/067ead88-9d6e-7e5e-8000-3c10ed6e5554._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.733Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.733Z",
    updatedAt: "2025-04-24T08:51:55.733Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 13,
    displayName: "The Paws Dog Accessory",
    description:
      "This tailor-cut, double-sided bandana has a distinctly USA attitude and look.\\n    Each bandana is made with love on the island of Bali by experienced and skilled teams.\\n    For your convenience, these bandanas are available in different sizes for pups of all sizes.\\n    For an eye-catching look, deck your doggy out in this bandana.\\n    For convenience, this accessory is made with 100% cotton for easy washing and long-lasting colors.\\n\\nRemember to measure your pet for the perfect fit. Show off your furry friend’s national pride with The Paws National Dog Bandana. This tailor-cut, double-sided bandana is inspired by tropical and urban locations, featuring a mix of bright colors and unique designs. Made with love on the island of Bali by an experienced and skilled team, this bandana is thoughtfully crafted for your furbaby. Perfect for any patriotic pup, this bandana comes in different sizes to fit tail waggers of all sizes. Made with 100% cotton, this bandana can be washed multiple times without losing its vibrant colors. Show off your barking BFF’s patriotic spirit with The Paws National Dog Bandana.",
    manufacturer: {
      id: 4,
      displayName: "The Paws",
      createdAt: "2025-04-24T08:51:55.718Z",
      updatedAt: "2025-04-24T08:51:55.718Z",
      deletedAt: null,
      version: 1,
    },
    price: 17.25,
    rating: 4.25,
    reviews: 0,
    category: "Dog Accessories",
    type: "bandana",
    colors: [
      {
        id: 13,
        major: "pattern, blue, red, white",
        sub: "grayish blue, red, white",
        r: 202,
        g: 208,
        b: 220,
      },
    ],
    size: "X-Large",
    weightRange: "[0,999]",
    season: "Year-Round",
    materials: [
      {
        id: 13,
        name: "Cotton",
        createdAt: "2025-04-24T08:51:55.743Z",
        deletedAt: null,
      },
    ],
    instructions: "Machine wash, tumble dry.",
    images: [
      {
        id: 13,
        url: "https://image.chewy.com/catalog/general/images/moe/067ead89-94da-7678-8000-d7cb23fc79c4._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.743Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.743Z",
    updatedAt: "2025-04-24T08:51:55.743Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 14,
    displayName: "The Paws Dog Accessory",
    description:
      "This casual T-shirt features multicolored stripes in a steamy, tropical-inspired style.\\n    Contrast-colored ribbed trim at the collar, armholes, and hem provide added comfort and ease of movement.\\n    The pullover, machine-washable design makes it easy to put on, take off, and keep clean.\\n    Available in multiple sizes so you can choose the perfect fit for your pet.\\n    Frisco products are crafted to deliver more happy moments together—from adorable apparel and exciting toys, to sturdy outdoor gear. Designed, tested and approved by the pet experts at Chewy.\\n\\nRemember to measure your pet to find the perfect fit in our updated Frisco apparel sizing. Bring the sizzling style of the tropics to your pet’s leisure wear wardrobe with this colorful pullover T-shirt from Frisco by Chewy. An array of bright horizontal stripes and contrast, ribbed trim at the collar, hem, and armholes make for an effortless outfit that’s still sure to impress. Getting it on and off is easy, just pull it over their head. The lightweight fabric and ribbed trim make it comfortable for them to wear, offering a snug fit that won’t impede their freedom of movement. Plus, it’s machine washable so keeping it clean is a cinch.",
    manufacturer: {
      id: 4,
      displayName: "The Paws",
      createdAt: "2025-04-24T08:51:55.718Z",
      updatedAt: "2025-04-24T08:51:55.718Z",
      deletedAt: null,
      version: 1,
    },
    price: 17.25,
    rating: 4.25,
    reviews: 0,
    category: "Dog Accessories",
    type: "bandana",
    colors: [
      {
        id: 14,
        major: "green",
        sub: "dark green, yellow, white",
        r: 87,
        g: 97,
        b: 98,
      },
    ],
    size: "X-Large",
    weightRange: "[55,75]",
    season: "Spring/Summer",
    materials: [
      {
        id: 14,
        name: "Cotton",
        createdAt: "2025-04-24T08:51:55.752Z",
        deletedAt: null,
      },
    ],
    instructions:
      "Turn inside out, Machine wash cold with like colors on gentle cycle. Only non-chlorine bleach when needed. Tumble dry low. Do not iron.",
    images: [
      {
        id: 14,
        url: "https://image.chewy.com/catalog/general/images/moe/067ead89-d9a9-76e5-8000-03f42840f60f._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.752Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.752Z",
    updatedAt: "2025-04-24T08:51:55.752Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 15,
    displayName: "Frisco Dog Clothing",
    description:
      "This casual T-shirt features multicolored stripes in a steamy, tropical-inspired style.\\n    Contrast-colored ribbed trim at the collar, armholes, and hem provide added comfort and ease of movement.\\n    The pullover, machine-washable design makes it easy to put on, take off, and keep clean.\\n    Available in multiple sizes so you can choose the perfect fit for your pet.\\n    Frisco products are crafted to deliver more happy moments together—from adorable apparel and exciting toys, to sturdy outdoor gear. Designed, tested and approved by the pet experts at Chewy.\\n\\nRemember to measure your pet to find the perfect fit in our updated Frisco apparel sizing. Bring the sizzling style of the tropics to your pet’s leisure wear wardrobe with this colorful pullover T-shirt from Frisco by Chewy. An array of bright horizontal stripes and contrast, ribbed trim at the collar, hem, and armholes make for an effortless outfit that’s still sure to impress. Getting it on and off is easy, just pull it over their head. The lightweight fabric and ribbed trim make it comfortable for them to wear, offering a snug fit that won’t impede their freedom of movement. Plus, it’s machine washable so keeping it clean is a cinch.",
    manufacturer: {
      id: 5,
      displayName: "Frisco",
      createdAt: "2025-04-24T08:51:55.761Z",
      updatedAt: "2025-04-24T08:51:55.761Z",
      deletedAt: null,
      version: 1,
    },
    price: 17.25,
    rating: 4.25,
    reviews: 1,
    category: "Dog Clothes",
    type: "shirt",
    colors: [
      {
        id: 15,
        major: "stripes",
        sub: "blue, red, green, orange",
        r: 55,
        g: 190,
        b: 247,
      },
    ],
    size: "X-Large",
    weightRange: "[55,75]",
    season: "Spring/Summer",
    materials: [
      {
        id: 15,
        name: "Polyester",
        createdAt: "2025-04-24T08:51:55.765Z",
        deletedAt: null,
      },
    ],
    instructions:
      "Turn inside out, Machine wash cold with like colors on gentle cycle. Only non-chlorine bleach when needed. Tumble dry low. Do not iron.",
    images: [
      {
        id: 15,
        url: "https://image.chewy.com/catalog/general/images/moe/067ab812-7a90-7958-8000-5d0bfa2f4f77._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.765Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.765Z",
    updatedAt: "2025-04-24T08:51:55.765Z",
    deletedAt: null,
    version: 1,
  },
];
