export const products = [
  {
    id: 1,
    displayName: "CuteBone Dog Clothing",
    description:
      "    These pajamas are made with soft, stretchy fabric for ultimate comfort and flexibility.\n    The convenient button/snap closure allows for easy on and off.\n    These pajamas provide extra warmth for cooler nights or lounging at home so your furbaby can be comfy and cozy.\n    The versatile design can be used as a stylish outfit for everyday wear.\n    You\u2019ll like that the durable material ensures long-lasting comfort for your furry friend.\n\nRemember to measure your pet for the perfect fit. Treat your big pup to the ultimate comfort and style with CuteBone Skull Big Dog Pajamas. These stretchy pajamas are perfect for medium to large-sized furbabies like pitbulls and golden retrievers. Made with soft, stretchy fabric, these pajamas allow your furry friend to move freely while staying cozy. Whether they need extra warmth on chilly nights, protection from allergens, or just a stylish outfit for everyday wear, these pajamas have got your barking BFF covered. Plus, the convenient button/snap closure makes it easy to put on and take off, so they\u2019re practical for everyday use. Whether it\u2019s bedtime, lounging, or a relaxing day at home, your pup will be snug and stylish in these durable and comfortable pajamas.",
    manufacturer: {
      id: 1,
      displayName: "CuteBone",
      createdAt: "2025-04-24T08:51:55.552Z",
      updatedAt: "2025-04-24T08:51:55.552Z",
      deletedAt: null,
      version: 1,
    },
    price: 29.99,
    rating: 4.3,
    reviews: 0,
    category: "Dog Clothes",
    type: "pajama",
    colors: [
      {
        id: 1,
        major: "black, white",
        category: "Dog Clothes",
        sub: "black, white",
        r: 23,
        g: 23,
        b: 23,
      },
    ],
    size: "Large",
    weightRange: "[45,60]",
    season: "Year-Round",
    materials: [
      {
        id: 1,
        name: "Polyester",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
    ],
    instructions: "Hand and machine washable.",
    images: [
      {
        id: 1,
        url: "https://image.chewy.com/catalog/general/images/moe/067577ba-4f5b-765b-8000-23ef5e105df4._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 2,
        url: "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 3,
        url: "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 4,
        url: "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.580Z",
    updatedAt: "2025-04-24T08:51:55.580Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 2,
    displayName: "CuteBone Dog Clothing",
    description:
      "    These pajamas are designed for medium to large-sized pups, providing comfort, warmth, and style.\n    Made from soft and stretchy fabric, these PJs were made for maximum comfort and flexibility.\n    For your convenience, these PJs have a button/snap closure for easy on and off.\n    These pup PJs are ideal for keeping your furbaby warm during cooler nights.\n    Best of all, these versatile pajamas can be used for lounging, extra warmth, or as a stylish everyday outfit.\n\nRemember to measure your pet for the perfect fit. Treat your furry friend to the ultimate comfort and style with CuteBone Dino Big Dog Pajamas. These pajamas are specially designed for medium to large-sized pups, like pitbulls and golden retrievers, to provide warmth, coziness, and a touch of fashion. The soft and stretchy fabric allows your furbaby to move freely and comfortably, making these PJs perfect for lounging at home or for extra warmth on chilly nights. With a convenient button/snap closure, these pajamas are easy to put on and take off, so they\u2019re a practical choice for pet parents. Whether your tail wagger needs extra warmth, protection from allergens, or a stylish outfit for everyday wear, these pajamas have got them covered. The durable material ensures long-lasting comfort without restricting movement, so they\u2019re grrrr-eat for bedtime, lounging, or just a relaxing day at home.",
    manufacturer: {
      id: 1,
      displayName: "CuteBone",
      createdAt: "2025-04-24T08:51:55.609Z",
      updatedAt: "2025-04-24T08:51:55.609Z",
      deletedAt: null,
      version: 1,
    },
    price: 29.0,
    rating: 0.0,
    reviews: 0,
    category: "Dog Clothes",
    type: "pajama",
    colors: [
      {
        id: 2,
        major: "white",
        sub: "white, pink, blue, orange",
        r: 255,
        g: 255,
        b: 255,
      },
    ],
    size: "X-Large",
    weightRange: "[60, 75]",
    season: "Year-Round",
    materials: [
      {
        id: 1,
        name: "Polyester",
        createdAt: "2025-04-24T08:51:55.614Z",
        deletedAt: null,
      },
    ],
    instructions: "Hand and machine washable.",
    images: [
      {
        id: 1,
        url: "https://image.chewy.com/catalog/general/images/moe/06757779-ffce-7d2e-8000-ade3ac88870b._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 2,
        url: "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 3,
        url: "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 4,
        url: "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.614Z",
    updatedAt: "2025-04-24T08:51:55.614Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 3,
    displayName: "CuteBone Dog Clothing",
    description:
      "This dress is made from 100% soft, lightweight, and stretchy material for ultimate comfort.\\n    For even more adorable appeal, this dress comes with a matching bow hair rope for an extra touch of charm.\\n    An easy pullover design allows for quick dressing and convenience.\\n    This dress is versatile for any occasion, from parties to everyday wear.\\n    You’ll love that it’s machine washable for easy cleaning and maintenance.\\n\\nRemember to measure your pet for the perfect fit. Dress your pup in style with the CuteBone Polka Dot Dog Mesh Sundress. Made from 100% soft, lightweight, and stretchy material, this breathable dress will keep your furry friend comfortable in any season. Each dress comes with a matching bow hair rope, adding an extra touch of charm to your pup’s look. The easy pullover design makes dressing a breeze, perfect for any occasion. Whether it’s a wedding, picnic, holiday, or just a day out, your pup will be the center of attention in this versatile and adorable dress. And don’t worry about keeping it clean—it’s machine washable and will maintain its softness and color after every wash. Just be sure to measure your barking BFF for the perfect fit.",
    manufacturer: {
      id: 1,
      displayName: "CuteBone",
      createdAt: "2025-04-24T08:51:55.624Z",
      updatedAt: "2025-04-24T08:51:55.624Z",
      deletedAt: null,
      version: 1,
    },
    price: 16.99,
    rating: 0.0,
    reviews: 0,
    category: "Dog Clothes",
    type: "pajama",
    colors: [
      {
        id: 3,
        major: "pink",
        sub: "soft pink",
        r: 226,
        g: 126,
        b: 147,
      },
    ],
    size: "Large",
    weightRange: null,
    season: "Fall/Winter",
    materials: [
      {
        id: 1,
        name: "Polyester",
        createdAt: "2025-04-24T08:51:55.629Z",
        deletedAt: null,
      },
    ],
    instructions: "Hand and Machine Washable.",
    images: [
      {
        id: 1,
        url: "https://image.chewy.com/catalog/general/images/moe/067577a7-b924-76cd-8000-59bdb7c87f9f._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 2,
        url: "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 3,
        url: "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 4,
        url: "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.629Z",
    updatedAt: "2025-04-24T08:51:55.629Z",
    deletedAt: null,
    version: 1,
  },
  {
    id: 4,
    displayName: "CuteBone Dog Clothing",
    description:
      "    These pajamas are designed for medium to large-sized pups, providing comfort, warmth, and style.\n    The soft and stretchy fabric allows for free movement, so your furbaby feels comfy and not restricted.\n    You\u2019ll love the convenient button/snap closure that allows for easy wear.\n    These PJs can be used for lounging, extra warmth, or as a stylish everyday outfit.\n    Feel good knowing these pajamas are made with durable material for long-lasting use.\n\nRemember to measure your pet for the perfect fit. Treat your furry friend to the ultimate comfort and style with CuteBone Duck Big Dog Pajamas. These pajamas are specially designed for medium to large-sized pups, such as pitbulls and golden retrievers, providing them with warmth, coziness, and a touch of fashion. The soft and stretchy fabric allows your furbaby to move freely, making it perfect for lounging at home or keeping them warm on chilly nights. With a convenient button/snap closure, these pajamas are easy to put on and take off, making them practical for everyday use. Whether your four-legged family member needs extra warmth, protection from allergens, or just a cute outfit for everyday wear, these pajamas have got you covered. Made with durable material, they are both comfortable and long-lasting, ensuring your tail wagger stays snug without any restrictions. So, whether it\u2019s bedtime, lounging, or a relaxing day at home, CuteBone Stretchy Pajamas are the perfect choice for your furry companion.",
    manufacturer: {
      id: 1,
      displayName: "CuteBone",
      createdAt: "2025-04-24T08:51:55.624Z",
      updatedAt: "2025-04-24T08:51:55.624Z",
      deletedAt: null,
      version: 1,
    },
    price: 29.99,
    rating: 0.0,
    reviews: 0,
    category: "Dog Clothes",
    type: "pajama",
    colors: [
      {
        id: 4,
        major: "blue, green, yellow",
        sub: "blue, green, yellow",
        r: 77,
        g: 172,
        b: 185,
      },
    ],
    size: "Large",
    weightRange: "[45,60]",
    season: "Year-Round",
    materials: [
      {
        id: 4,
        name: "Polyester",
        createdAt: "2025-04-24T08:51:55.640Z",
        deletedAt: null,
      },
    ],
    instructions: "Hand and machine washable.",
    images: [
      {
        id: 1,
        url: "https://image.chewy.com/catalog/general/images/moe/067577b0-0f65-7821-8000-f769d9da0a8c._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 2,
        url: "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 3,
        url: "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
      {
        id: 4,
        url: "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
        description: "",
        createdAt: "2025-04-24T08:51:55.580Z",
        deletedAt: null,
      },
    ],
    createdAt: "2025-04-24T08:51:55.640Z",
    updatedAt: "2025-04-24T08:51:55.640Z",
    deletedAt: null,
    version: 1,
  },
];
// export const products = [
//   {
//     id: 1,
//     name: "CuteBone Skull Big Dog Pajamas, Black & White, Large",
//     price: 29.99,
//     rating: 4.3,
//     image_url:
//       "https://image.chewy.com/catalog/general/images/moe/067577ba-4f5b-765b-8000-23ef5e105df4._AC_SL600_V528090960_.jpg",
//     additional_images: [
//       "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
//     ],
//     description:
//       "    These pajamas are made with soft, stretchy fabric for ultimate comfort and flexibility.\n    The convenient button/snap closure allows for easy on and off.\n    These pajamas provide extra warmth for cooler nights or lounging at home so your furbaby can be comfy and cozy.\n    The versatile design can be used as a stylish outfit for everyday wear.\n    You\u2019ll like that the durable material ensures long-lasting comfort for your furry friend.\n\nRemember to measure your pet for the perfect fit. Treat your big pup to the ultimate comfort and style with CuteBone Skull Big Dog Pajamas. These stretchy pajamas are perfect for medium to large-sized furbabies like pitbulls and golden retrievers. Made with soft, stretchy fabric, these pajamas allow your furry friend to move freely while staying cozy. Whether they need extra warmth on chilly nights, protection from allergens, or just a stylish outfit for everyday wear, these pajamas have got your barking BFF covered. Plus, the convenient button/snap closure makes it easy to put on and take off, so they\u2019re practical for everyday use. Whether it\u2019s bedtime, lounging, or a relaxing day at home, your pup will be snug and stylish in these durable and comfortable pajamas.",
//   },
//   {
//     id: 2,
//     name: "CuteBone Dino Big Dog Pajamas, Pink & White, X-Large",
//     price: 29.0,
//     rating: 0.0,
//     image_url:
//       "https://image.chewy.com/catalog/general/images/moe/06757779-ffce-7d2e-8000-ade3ac88870b._AC_SL600_V528090960_.jpg",
//     additional_images: [
//       "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
//     ],
//     description:
//       "    These pajamas are designed for medium to large-sized pups, providing comfort, warmth, and style.\n    Made from soft and stretchy fabric, these PJs were made for maximum comfort and flexibility.\n    For your convenience, these PJs have a button/snap closure for easy on and off.\n    These pup PJs are ideal for keeping your furbaby warm during cooler nights.\n    Best of all, these versatile pajamas can be used for lounging, extra warmth, or as a stylish everyday outfit.\n\nRemember to measure your pet for the perfect fit. Treat your furry friend to the ultimate comfort and style with CuteBone Dino Big Dog Pajamas. These pajamas are specially designed for medium to large-sized pups, like pitbulls and golden retrievers, to provide warmth, coziness, and a touch of fashion. The soft and stretchy fabric allows your furbaby to move freely and comfortably, making these PJs perfect for lounging at home or for extra warmth on chilly nights. With a convenient button/snap closure, these pajamas are easy to put on and take off, so they\u2019re a practical choice for pet parents. Whether your tail wagger needs extra warmth, protection from allergens, or a stylish outfit for everyday wear, these pajamas have got them covered. The durable material ensures long-lasting comfort without restricting movement, so they\u2019re grrrr-eat for bedtime, lounging, or just a relaxing day at home.",
//   },
//   {
//     id: 3,
//     name: "CuteBone Turtleneck Dog Pajamas, Pink, Large",
//     price: 16.99,
//     rating: 0.0,
//     image_url:
//       "https://image.chewy.com/catalog/general/images/moe/067577a7-b924-76cd-8000-59bdb7c87f9f._AC_SL600_V528090960_.jpg",
//     additional_images: [
//       "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
//     ],
//     description:
//       "    These pajamas are made from premium Dralon material to ensure durability and softness.\n    The turtleneck design provides additional warmth for your little pup during cold weather.\n    The stretchy fabric allows for easy movement and a comfortable fit for your furry friend.\n    These versatile PJs are perfect for everyday wear, lounging, bedtime, and keeping warm during indoor activities.\n    The pullover design makes it simple to put on and take off, providing a hassle-free dressing experience for pet parents.\n\nRemember to measure your pet for the perfect fit. Ensure your small pup stays warm and stylish with the CuteBone Turtleneck Dog Pajamas.",
//   },
//   {
//     id: 4,
//     name: "CuteBone Duck Big Dog Pajamas, Blue-Green & Yellow, Large",
//     price: 29.99,
//     rating: 0.0,
//     image_url:
//       "https://image.chewy.com/catalog/general/images/moe/067577b0-0f65-7821-8000-f769d9da0a8c._AC_SL600_V528090960_.jpg",
//     additional_images: [
//       "https://image.chewy.com/catalog/general/images/moe/067927d5-80cf-7d50-8000-97095cda2197._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/06790575-f4f6-7a1b-8000-3ae8a7ca7f8b._AC_SL600_V528090960_.jpg",
//       "https://image.chewy.com/catalog/general/images/moe/067e449a-2fac-77ea-8000-4e3ae1b71354._AC_SL600_V528090960_.jpg",
//     ],
//     description:
//       "    These pajamas are designed for medium to large-sized pups, providing comfort, warmth, and style.\n    The soft and stretchy fabric allows for free movement, so your furbaby feels comfy and not restricted.\n    You\u2019ll love the convenient button/snap closure that allows for easy wear.\n    These PJs can be used for lounging, extra warmth, or as a stylish everyday outfit.\n    Feel good knowing these pajamas are made with durable material for long-lasting use.\n\nRemember to measure your pet for the perfect fit. Treat your furry friend to the ultimate comfort and style with CuteBone Duck Big Dog Pajamas. These pajamas are specially designed for medium to large-sized pups, such as pitbulls and golden retrievers, providing them with warmth, coziness, and a touch of fashion. The soft and stretchy fabric allows your furbaby to move freely, making it perfect for lounging at home or keeping them warm on chilly nights. With a convenient button/snap closure, these pajamas are easy to put on and take off, making them practical for everyday use. Whether your four-legged family member needs extra warmth, protection from allergens, or just a cute outfit for everyday wear, these pajamas have got you covered. Made with durable material, they are both comfortable and long-lasting, ensuring your tail wagger stays snug without any restrictions. So, whether it\u2019s bedtime, lounging, or a relaxing day at home, CuteBone Stretchy Pajamas are the perfect choice for your furry companion.",
//   },
// ];
